model: openai/gpt-4o-mini
edit-format: diff
auto-lint: true
lint-cmd:
  - "python: ruff check --fix"
  - "python: black"
  - "javascript: eslint --fix"
  - "typescript: eslint --fix"
  - "markdown: prettier --write"
  - "yaml: yamllint"

