version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cyberner-api
    environment:
      QDRANT_URL: http://localhost:6333
      QDRANT_COLLECTION: heva_docs
      VECTORS_SIZE: 384
    ports:
      - "8000:8000"
    restart: unless-stopped
