version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

  api:
    build: ./api
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
    restart: unless-stopped

volumes:
  qdrant_data:
