name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt || true
      - run: pip install ruff black pytest pytest-cov mypy bandit pip-audit

      - name: Ruff (lint)
        run: ruff check --output-format=github

      - name: Black (format check)
        run: black --check .

      - name: Mypy (type check)
        run: mypy .

      - name: Bandit (security)
        run: bandit -r .

      - name: Tests
        run: pytest -q --cov=. --cov-report=xml --cov-report=term
